package me.banbeucmas.oregen3.listener;

import com.cryptomorin.xseries.XBlock;
import com.cryptomorin.xseries.XMaterial;
import me.banbeucmas.oregen3.Oregen3;
import me.banbeucmas.oregen3.data.Generator;
import me.banbeucmas.oregen3.util.BlockChecker;
import net.Indyuce.mmoitems.MMOItems;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.block.Block;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.inventory.ItemStack;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;

public class BlockBreakListener implements Listener {
    private Oregen3 plugin;

    public BlockBreakListener(Oregen3 plugin) {
        this.plugin = plugin;
    }

    private int checkMode(Block block,
                              int waterBlock,
                              int lavaBlock,
                              int waterLava) {
        Block[] blocks =  new Block[BlockChecker.FACES.length];
        for (int i = 0; i < blocks.length; i++) {
            blocks[i] = block.getRelative(BlockChecker.FACES[i]);
        }

        for (int i = 0; i < blocks.length; i++) {
            boolean blockIWater = XBlock.isWater(blocks[i].getType());
            boolean blockILava = XBlock.isLava(blocks[i].getType());
            for (int j = 0; j < blocks.length; j++) {
                if (i == j) continue;

                boolean blockJLava = XBlock.isLava(blocks[j].getType());
                boolean blockJBlock = plugin.getBlockChecker().isBlock(blocks[j]);
                if (waterBlock >= 0 && blockIWater && blockJBlock) {
                    return waterBlock;
                }
                if (lavaBlock >= 0 && blockILava && blockJBlock) {
                    return lavaBlock;
                }
                if (waterLava >= 0 && blockIWater && blockJLava) {
                    return waterLava;
                }
            }
        }
        return -1;
    }

    @EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = true)
    public void onBlockBreakDrop(BlockBreakEvent event) {
        Block block = event.getBlock();
        
        // We only want to process drops for blocks that were generated by Oregen3
        // We DON'T remove it here anymore, we only 'get' it.
        // It will be removed in the onBlockBreak handler below.
        String generatorId = plugin.getDataManager().getGeneratedBlocks().get(block.getLocation());
        if (generatorId == null) return;

        Generator generator = plugin.getDataManager().getGenerators().get(generatorId);
        if (generator == null || generator.getDrops().isEmpty()) return;

        if (generator.isReplaceDrops()) {
            event.setDropItems(false);
        }

        boolean mmoItemsEnabled = Bukkit.getPluginManager().isPluginEnabled("MMOItems");

        for (Map.Entry<String, Double> entry : generator.getDrops().entrySet()) {
            if (ThreadLocalRandom.current().nextDouble(100) < entry.getValue()) {
                String dropStr = entry.getKey();
                ItemStack item = null;
                if (dropStr.startsWith("mmoitems-") && mmoItemsEnabled) {
                    String[] split = dropStr.substring(9).split(":", 2);
                    if (split.length == 2) {
                        item = getMMOItem(split[0], split[1]);
                    }
                } else {
                    Optional<XMaterial> xMaterial = XMaterial.matchXMaterial(dropStr);
                    if (xMaterial.isPresent()) {
                        item = xMaterial.get().parseItem();
                    }
                }

                if (item != null) {
                    block.getWorld().dropItemNaturally(block.getLocation(), item);
                }
            }
        }
    }

    private ItemStack getMMOItem(String type, String id) {
        try {
            net.Indyuce.mmoitems.api.Type mmoType = net.Indyuce.mmoitems.api.Type.get(type.trim().toUpperCase());
            if (mmoType != null) {
                return MMOItems.plugin.getItem(mmoType, id.trim());
            }
        } catch (Throwable t) {
            try {
                return MMOItems.plugin.getItem(MMOItems.plugin.getTypes().get(type.trim().toUpperCase()), id.trim());
            } catch (Throwable t2) {
                // Ignore
            }
        }
        return null;
    }

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBlockBreak(BlockBreakEvent event) {
        Block block = event.getBlock();
        
        // Fix: Only trigger regeneration if the block was originally an Oregen3 generated block
        // This prevents every block in the world from turning into cobblestone
        String generatorId = plugin.getDataManager().getGeneratedBlocks().remove(block.getLocation());
        if (generatorId == null) return;

        FileConfiguration config = plugin.getConfig();
        int waterBlock = config.getBoolean("mode.waterBlock") ?
                config.getInt("global.generators.check-regen.mode.waterBlock", -1) : -1;
        int lavaBlock = config.getBoolean("mode.lavaBlock") ?
                config.getInt("global.generators.check-regen.mode.lavaBlock", -1) : -1;
        int waterLava = config.getBoolean("mode.waterLava") ?
                config.getInt("global.generators.check-regen.mode.waterLava", -1) : -1;

        if (waterBlock < 0 && lavaBlock < 0 && waterLava < 0) return;

        int delay = checkMode(block, waterBlock, lavaBlock, waterLava);
        
        if (delay > 0) {
            OfflinePlayer owner = plugin.getUtils().getOwner(block.getLocation());
            if (owner != null) {
                double level = plugin.getUpgradeManager().getUpgradeLevel(owner.getUniqueId(), "linhmach");
                if (level > 0) {
                    double percentPerLevel = config.getDouble("upgrade-gui.upgrades.linhmach.percent_per_level", 5.0);
                    double speedFactor = 1.0 + (percentPerLevel * level / 100.0);
                    delay = (int) Math.round(delay / speedFactor);
                }
            }
        }

        if (delay <= 0) {
            plugin.getBlockEventHandler().generateBlock(block);
        }
        else {
            plugin.getServer().getScheduler().runTaskLater(plugin,
                    () -> plugin.getBlockEventHandler().generateBlock(block), delay);
        }
    }
}
